# Generated by Django 5.1.4 on 2024-12-14 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
